---

- name: Get the list of services
  service_facts:

- name: Disable WiFi in raspberry boot config
  lineinfile:
    dest: /boot/config.txt
    line: 'dtoverlay=disable-wifi'
    state: present
  notify:
    - reboot-host

- name: disable WPA Supplicant service
  systemd:
    name: wpa_supplicant
    enabled: false
    masked: true
  when: "'wpa_supplicant.service' in services"
  notify:
    - reboot-host
